### PR TITLE
Added automatic palette generation to conv_to_sv

### PR DESCRIPTION
**Pull request by ijustlovemath**
So I figured that palette generation was a little too... manual, and took it upon myself to automagically generate a minimal palette from the colors in the image. It works by basically lumping colors within a certain distance of one another together, thus saving room in the palette. Then, I rolled this palette into the SV generation code to make it super easy to use. Also added prompts to show the usage of the script, etc. Try it with GalagaLogo.png, an image I'm PR'ing into sprite_originals

### CODE REVIEW

**Comment by atrifex** [comment]
Haha cool. I will make sure its working at some point and merge it then. Slightly busy right now. 

You should think about being a TA if you enjoy doing this stuff so much.

**Comment by ijustlovemath** [comment]
looks like I don't have upload access, but I can email you the image if you would add it. I think it's a really cool example, as it reduced our palette from needing 256 colors in the red to just 8, and similarly for the others.

**Comment by ijustlovemath** [comment]
But yeah, I think I may be if I get the A :)

**Comment by atrifex** [comment]
Cool! Yeah let me know if you want me to recommend you to the professor!

Also, if you get the position then I can just make you a collaborator so that you can directly add cool new features!

**Comment by Atrifex** [comment]
Also my email is rrthakk2@illinois.edu if you still want to send me the image.

**Comment by ijustlovemath** [comment]
Definitely, I'd appreciate it! You have my email/netid now.

**Pull request merged**
